title: Fuel for your heavy metal fire
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 1
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c27b6533-1e65-4e65-8dbe-2119632684b3.png
author:
  url: www.progpolar.com
  name: ProgPolar
  email: progpolar@gmail.com
name: ProgPolar
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/bb45d162-1532-4074-830b-13d403fefcd5.png
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.2881008090917021
  saturation: 0.2143665419425815
  brandColors:
    - '#262626'
    - '#b5b5b5'
    - '#dddddf'
    - '#989898'
    - '#6a6b6d'
  lightness: 0.2052786219865084
  rhythmicContrast: 0.885577607434243
typography_spectrum: 0.1574468
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/484cc821-31c1-4972-8b6e-6d4e0ac743a7.svg
